var Profiles=[
	{
		'Name':'Jerusalem',
		'File':'Jerusalem.jpg',
		'pointarr':'JerusalemPt',
		'offsetTop':'-138px',
		'offsetLeft':'34px',
		'StartIndex':371,
		'zoom':0.8,
		'GpoupList':'\
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;Флаги</span></h4> \
		</div> \
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"> \
		<span class="icon"></span><span class="text">&nbsp;Тамплиеры</span></h4> \
		</div> \
		<div href="#" class="list-group-item autohist"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;История</span></h4> \
		</div> \
		',
	},
	{
		'Name':'Acre',
		'File':'Acre.jpg',
		'pointarr':'AcrePt',
		'offsetTop':'-492px',
		'offsetLeft':'-273px',
		'StartIndex':261,
		'zoom':0.8,
		'GpoupList':'\
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;Флаги</span></h4> \
		</div> \
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"> \
		<span class="icon"></span><span class="text">&nbsp;Тамплиеры</span></h4> \
		</div> \
		<div href="#" class="list-group-item autohist"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;История</span></h4> \
		</div> \
		',
	},
	{
		'Name':'Damascus',
		'File':'Damascus.jpg',
		'pointarr':'DamascusPt',
		'offsetTop':'-205px',
		'offsetLeft':'-100px',
		'StartIndex':21,
		'zoom':0.8,
		'GpoupList':'\
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;Флаги</span></h4> \
		</div> \
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"> \
		<span class="icon"></span><span class="text">&nbsp;Тамплиеры</span></h4> \
		</div> \
		<div href="#" class="list-group-item autohist"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;История</span></h4> \
		</div> \
		',
	},
	{
		'Name':'Kingdom',
		'File':'Kingdom.jpg',
		'pointarr':'KingdomPt',
		'offsetTop':'-424px',
		'offsetLeft':'-93px',
		'StartIndex':131,
		'zoom':0.8,
		'GpoupList':'\
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;Флаги</span></h4> \
		</div> \
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"> \
		<span class="icon"></span><span class="text">&nbsp;Тамплиеры</span></h4> \
		</div> \
		<div href="#" class="list-group-item autohist"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;История</span></h4> \
		</div> \
		',
	},
	{
		'Name':'Masyaf',
		'File':'Masyaf.jpg',
		'pointarr':'MasyafPt',
		'offsetTop':'-188px',
		'offsetLeft':'226px',
		'StartIndex':1,
		'zoom':0.8,
		'GpoupList':'\
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;В первую очередь</span></h4> \
		</div> \
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"> \
		<span class="icon"></span><span class="text">&nbsp;Во вторую очередь</span></h4> \
		</div> \
		<div href="#" class="list-group-item autohist"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;История</span></h4> \
		</div> \
		',
	},
]

var JerusalemPt=[
	{
		'Name':'На крыше, 1 уровень',
		'CoordX':'674px',
		'CoordY':'612px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, в пролете.',
		'CoordX':'692px',
		'CoordY':'711px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'674px',
		'CoordY':'768px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер под 2 мостами.',
		'CoordX':'653px',
		'CoordY':'641px',
		'Groups':'[1]',
	},
	{
		'Name':'На крыше',
		'CoordX':'717px',
		'CoordY':'418px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, над лоджией',
		'CoordX':'625px',
		'CoordY':'379px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на мосту, у ворот.',
		'CoordX':'559px',
		'CoordY':'339px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше,1 уровень',
		'CoordX':'708px',
		'CoordY':'314px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, рядом со стеной',
		'CoordX':'623px',
		'CoordY':'206px',
		'Groups':'[0]',
	},
	{
		'Name':'Во дворике, в углу',
		'CoordX':'628px',
		'CoordY':'116px',
		'Groups':'[0]',
	},
	{
		'Name':'В храме, на балках',
		'CoordX':'719px',
		'CoordY':'111px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер в углу',
		'CoordX':'782px',
		'CoordY':'39px',
		'Groups':'[1]',
	},
	{
		'Name':'На крыше здания, рядом со стеной',
		'CoordX':'896px',
		'CoordY':'77px',
		'Groups':'[0]',
	},
	{
		'Name':'Выше крыши, на балках',
		'CoordX':'1149px',
		'CoordY':'88px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер в углу',
		'CoordX':'1084px',
		'CoordY':'86px',
		'Groups':'[1]',
	},
	{
		'Name':'На крыше',
		'CoordX':'1073px',
		'CoordY':'161px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыльце, в проходе.',
		'CoordX':'808px',
		'CoordY':'574px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, у стены, в тупике.',
		'CoordX':'878px',
		'CoordY':'612px',
		'Groups':'[0]',
	},
	{
		'Name':'Во дворе, на шпиле',
		'CoordX':'883px',
		'CoordY':'468px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, где откос',
		'CoordX':'820px',
		'CoordY':'448px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, рядом с лавкой.',
		'CoordX':'1023px',
		'CoordY':'373px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, за блоком.',
		'CoordX':'1018px',
		'CoordY':'413px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, у стены, в проулке, рядом с лестницей.',
		'CoordX':'1123px',
		'CoordY':'234px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на шпиле',
		'CoordX':'992px',
		'CoordY':'244px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, у стены.',
		'CoordX':'982px',
		'CoordY':'202px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше беседки',
		'CoordX':'869px',
		'CoordY':'162px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'905px',
		'CoordY':'296px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, перед базаром, в углу',
		'CoordX':'817px',
		'CoordY':'307px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше базара',
		'CoordX':'767px',
		'CoordY':'282px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'967px',
		'CoordY':'885px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер в углу',
		'CoordX':'1082px',
		'CoordY':'913px',
		'Groups':'[1]',
	},
	{
		'Name':'Рядом с прудом',
		'CoordX':'1127px',
		'CoordY':'582px',
		'Groups':'[0]',
	},
	{
		'Name':'На акре',
		'CoordX':'1054px',
		'CoordY':'577px',
		'Groups':'[0]',
	},
	{
		'Name':'На балконе',
		'CoordX':'1005px',
		'CoordY':'482px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на шпиле',
		'CoordX':'1106px',
		'CoordY':'455px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, в проулке',
		'CoordX':'1143px',
		'CoordY':'443px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, рядом с трубой.',
		'CoordX':'1161px',
		'CoordY':'542px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, 1 уровень.',
		'CoordX':'677px',
		'CoordY':'861px',
		'Groups':'[0]',
	},
	{
		'Name':'На помосте',
		'CoordX':'644px',
		'CoordY':'897px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, 1 уровень',
		'CoordX':'763px',
		'CoordY':'950px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'780px',
		'CoordY':'1019px',
		'Groups':'[0]',
	},
	{
		'Name':'Внутри сарая',
		'CoordX':'750px',
		'CoordY':'1062px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше беседки.',
		'CoordX':'793px',
		'CoordY':'1122px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, рядом с лучником',
		'CoordX':'705px',
		'CoordY':'1092px',
		'Groups':'[0]',
	},
	{
		'Name':'На шпиле, между зданиями',
		'CoordX':'703px',
		'CoordY':'1034px',
		'Groups':'[0]',
	},
	{
		'Name':'Во дворе, под настилом',
		'CoordX':'631px',
		'CoordY':'996px',
		'Groups':'[0]',
	},
	{
		'Name':'Во дворе, рядом с настилом.',
		'CoordX':'601px',
		'CoordY':'957px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше-помосте, 1 уровень.',
		'CoordX':'585px',
		'CoordY':'904px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер',
		'CoordX':'625px',
		'CoordY':'838px',
		'Groups':'[1]',
	},
	{
		'Name':'На крыше, рядом с переходом к другому зданию.',
		'CoordX':'498px',
		'CoordY':'920px',
		'Groups':'[0]',
	},
	{
		'Name':'Во дворе, под навесом',
		'CoordX':'391px',
		'CoordY':'912px',
		'Groups':'[0]',
	},
	{
		'Name':'На помосте, над скамейкой.',
		'CoordX':'306px',
		'CoordY':'879px',
		'Groups':'[0]',
	},
	{
		'Name':'В дырке на крыше дома, с забором.',
		'CoordX':'331px',
		'CoordY':'959px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'425px',
		'CoordY':'1025px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, 1 уровень',
		'CoordX':'364px',
		'CoordY':'1028px',
		'Groups':'[0]',
	},
	{
		'Name':'На балконе.',
		'CoordX':'399px',
		'CoordY':'1086px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, в проулке.',
		'CoordX':'261px',
		'CoordY':'1171px',
		'Groups':'[0]',
	},
	{
		'Name':'На террасе-корыте.',
		'CoordX':'310px',
		'CoordY':'1259px',
		'Groups':'[0]',
	},
	{
		'Name':'На терасе, в углублении',
		'CoordX':'474px',
		'CoordY':'1133px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер, стоит на крыше, 1 уровень.',
		'CoordX':'476px',
		'CoordY':'1163px',
		'Groups':'[1]',
	},
	{
		'Name':'Во дворе, между пальмами',
		'CoordX':'505px',
		'CoordY':'1114px',
		'Groups':'[0]',
	},
	{
		'Name':'Под мостиком, между домами.',
		'CoordX':'563px',
		'CoordY':'1097px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на балконе',
		'CoordX':'550px',
		'CoordY':'1039px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'603px',
		'CoordY':'1088px',
		'Groups':'[0]',
	},
	{
		'Name':'Над балконом',
		'CoordX':'583px',
		'CoordY':'1179px',
		'Groups':'[0]',
	},
	{
		'Name':'Над навесом.',
		'CoordX':'605px',
		'CoordY':'1163px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер в углу',
		'CoordX':'670px',
		'CoordY':'1247px',
		'Groups':'[1]',
	},
	{
		'Name':'В проулке, на земле.',
		'CoordX':'875px',
		'CoordY':'912px',
		'Groups':'[0]',
	},
	{
		'Name':'На помосте, у стены дома.',
		'CoordX':'866px',
		'CoordY':'826px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'885px',
		'CoordY':'708px',
		'Groups':'[0]',
	},
	{
		'Name':'На балконе',
		'CoordX':'823px',
		'CoordY':'776px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'775px',
		'CoordY':'775px',
		'Groups':'[0]',
	},
	{
		'Name':'Под навесом, между домами',
		'CoordX':'772px',
		'CoordY':'823px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, в проулке.',
		'CoordX':'721px',
		'CoordY':'838px',
		'Groups':'[0]',
	},
	{
		'Name':'На балконе',
		'CoordX':'542px',
		'CoordY':'719px',
		'Groups':'[0]',
	},
	{
		'Name':'В фонтане',
		'CoordX':'498px',
		'CoordY':'767px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше часовни',
		'CoordX':'514px',
		'CoordY':'805px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'477px',
		'CoordY':'410px',
		'Groups':'[0]',
	},
	{
		'Name':'Сбоку дома, на навесе',
		'CoordX':'434px',
		'CoordY':'411px',
		'Groups':'[0]',
	},
	{
		'Name':'На навесе',
		'CoordX':'475px',
		'CoordY':'490px',
		'Groups':'[0]',
	},
	{
		'Name':'На помосте, почти у земли',
		'CoordX':'551px',
		'CoordY':'497px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, в углу дома',
		'CoordX':'537px',
		'CoordY':'537px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'574px',
		'CoordY':'459px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома, между верандой и лестницей.',
		'CoordX':'653px',
		'CoordY':'534px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'495px',
		'CoordY':'596px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на веранде',
		'CoordX':'408px',
		'CoordY':'558px',
		'Groups':'[0]',
	},
	{
		'Name':'На сетчатом навесе.',
		'CoordX':'353px',
		'CoordY':'570px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер в тупике',
		'CoordX':'417px',
		'CoordY':'838px',
		'Groups':'[1]',
	},
	{
		'Name':'На балконе.',
		'CoordX':'466px',
		'CoordY':'849px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'467px',
		'CoordY':'820px',
		'Groups':'[0]',
	},
	{
		'Name':'За стеной, почти на земле, на тачке',
		'CoordX':'441px',
		'CoordY':'810px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, 1 уровень',
		'CoordX':'311px',
		'CoordY':'805px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'306px',
		'CoordY':'750px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, на столе.',
		'CoordX':'254px',
		'CoordY':'748px',
		'Groups':'[0]',
	},
	{
		'Name':'В фонтане',
		'CoordX':'184px',
		'CoordY':'692px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на веранде.',
		'CoordX':'239px',
		'CoordY':'626px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер на крыше',
		'CoordX':'272px',
		'CoordY':'526px',
		'Groups':'[1]',
	},
	{
		'Name':'На земле',
		'CoordX':'285px',
		'CoordY':'542px',
		'Groups':'[0]',
	},
	{
		'Name':'У стены, нижний уровень',
		'CoordX':'185px',
		'CoordY':'564px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше',
		'CoordX':'125px',
		'CoordY':'457px',
		'Groups':'[0]',
	},
	{
		'Name':'На деревянных мостках',
		'CoordX':'256px',
		'CoordY':'469px',
		'Groups':'[0]',
	},
	{
		'Name':'На мосту, между зданиями',
		'CoordX':'431px',
		'CoordY':'632px',
		'Groups':'[0]',
	},
	{
		'Name':'На стене дома на мостках',
		'CoordX':'496px',
		'CoordY':'639px',
		'Groups':'[0]',
	},
	{
		'Name':'Наверху, 1 уровень, на веранде.',
		'CoordX':'520px',
		'CoordY':'675px',
		'Groups':'[0]',
	},
	{
		'Name':'Тамплиер посреди улицы.',
		'CoordX':'475px',
		'CoordY':'674px',
		'Groups':'[1]',
	},
	{
		'Name':'На деревянном помосте, у стены.',
		'CoordX':'375px',
		'CoordY':'672px',
		'Groups':'[0]',
	},
	{
		'Name':'На террасе, почти на земле.',
		'CoordX':'430px',
		'CoordY':'742px',
		'Groups':'[0]',
	},
	{
		'Name':'На земле, напротив повозки с сеном',
		'CoordX':'205px',
		'CoordY':'993px',
		'Groups':'[0]',
	},
	{
		'Name':'Во дворе, в углу.',
		'CoordX':'207px',
		'CoordY':'812px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на шпиле',
		'CoordX':'304px',
		'CoordY':'1143px',
		'Groups':'[0]',
	},
];
var AcrePt=[
	{
		'Name' : 'Внизу',
		'CoordX' : '1014px',
		'CoordY' : '1087px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, в углу.',
		'CoordX' : '682px',
		'CoordY' : '1048px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В развалинах дома',
		'CoordX' : '496px',
		'CoordY' : '971px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балке, между домами.',
		'CoordX' : '388px',
		'CoordY' : '1055px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '303px',
		'CoordY' : '1004px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'У обрыва',
		'CoordX' : '247px',
		'CoordY' : '1040px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, на 1 уровне',
		'CoordX' : '359px',
		'CoordY' : '841px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле',
		'CoordX' : '430px',
		'CoordY' : '874px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер, на земле в развалинах дома.',
		'CoordX' : '348px',
		'CoordY' : '904px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Внизу, у стены, в кустах.',
		'CoordX' : '321px',
		'CoordY' : '725px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, между домами',
		'CoordX' : '373px',
		'CoordY' : '620px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Сектор дома, 1 уровень, рядом с первой обзорной башней.',
		'CoordX' : '399px',
		'CoordY' : '575px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '470px',
		'CoordY' : '691px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, у ворот',
		'CoordX' : '471px',
		'CoordY' : '554px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '561px',
		'CoordY' : '593px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, в обломках дома',
		'CoordX' : '897px',
		'CoordY' : '666px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В фонтане',
		'CoordX' : '1062px',
		'CoordY' : '566px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Крыша стены, 1 уровень',
		'CoordX' : '1129px',
		'CoordY' : '570px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер внизу',
		'CoordX' : '976px',
		'CoordY' : '471px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На стене, на помосте.',
		'CoordX' : '912px',
		'CoordY' : '475px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, под навесом',
		'CoordX' : '1119px',
		'CoordY' : '709px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в углу',
		'CoordX' : '1254px',
		'CoordY' : '534px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Внизу, в углу, у ворот.',
		'CoordX' : '1229px',
		'CoordY' : '791px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в угу',
		'CoordX' : '1309px',
		'CoordY' : '870px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше полу-башни (рядом с обзорной башней).',
		'CoordX' : '1077px',
		'CoordY' : '847px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, 1 уровень.',
		'CoordX' : '1096px',
		'CoordY' : '930px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На помосте, вдоль стены',
		'CoordX' : '983px',
		'CoordY' : '945px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '881px',
		'CoordY' : '1024px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше дома, в дер. треугольнике',
		'CoordX' : '728px',
		'CoordY' : '937px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше дома, в корыте',
		'CoordX' : '628px',
		'CoordY' : '863px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше дома',
		'CoordX' : '704px',
		'CoordY' : '817px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, в тупике.',
		'CoordX' : '527px',
		'CoordY' : '795px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, в пролете',
		'CoordX' : '614px',
		'CoordY' : '737px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше в корыте',
		'CoordX' : '912px',
		'CoordY' : '874px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На дороге валялся, вне стен здания.',
		'CoordX' : '819px',
		'CoordY' : '879px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внутри базара, на помосте',
		'CoordX' : '782px',
		'CoordY' : '841px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, под охраной',
		'CoordX' : '710px',
		'CoordY' : '599px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер во дворе',
		'CoordX' : '1052px',
		'CoordY' : '1172px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Между крыш, в ложбинке',
		'CoordX' : '1088px',
		'CoordY' : '1199px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '949px',
		'CoordY' : '1188px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе',
		'CoordX' : '289px',
		'CoordY' : '1202px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в углу',
		'CoordX' : '219px',
		'CoordY' : '1185px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На земле, в углублении из растений.',
		'CoordX' : '539px',
		'CoordY' : '1148px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В центре фонтана',
		'CoordX' : '746px',
		'CoordY' : '1158px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Над балконом',
		'CoordX' : '781px',
		'CoordY' : '1301px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '889px',
		'CoordY' : '1331px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле',
		'CoordX' : '1005px',
		'CoordY' : '1457px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внутри крепости',
		'CoordX' : '1080px',
		'CoordY' : '1405px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На козырьке, со стороны моря.',
		'CoordX' : '1138px',
		'CoordY' : '1573px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1054px',
		'CoordY' : '1663px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер на крыше собора',
		'CoordX' : '851px',
		'CoordY' : '1535px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На шпиле',
		'CoordX' : '838px',
		'CoordY' : '1591px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '838px',
		'CoordY' : '1693px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '602px',
		'CoordY' : '1655px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На набережной',
		'CoordX' : '650px',
		'CoordY' : '1866px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На стене, на крыше',
		'CoordX' : '404px',
		'CoordY' : '1804px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На стене, на крыше, центральная башня',
		'CoordX' : '483px',
		'CoordY' : '1866px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В башне, наверху, за охранником.',
		'CoordX' : '390px',
		'CoordY' : '2062px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На помосте, не на стене',
		'CoordX' : '298px',
		'CoordY' : '1867px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '709px',
		'CoordY' : '1757px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, в углу.',
		'CoordX' : '485px',
		'CoordY' : '1547px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На помосте, со стороны моря',
		'CoordX' : '494px',
		'CoordY' : '1457px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, под навесом, рядом со спасаемым жителем.',
		'CoordX' : '612px',
		'CoordY' : '1382px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В проулке, на балконе',
		'CoordX' : '479px',
		'CoordY' : '1316px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '551px',
		'CoordY' : '1281px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, под лестницей',
		'CoordX' : '467px',
		'CoordY' : '1220px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '365px',
		'CoordY' : '1206px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Над балконом, сбоку',
		'CoordX' : '362px',
		'CoordY' : '1265px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, около фонтана',
		'CoordX' : '681px',
		'CoordY' : '1241px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '728px',
		'CoordY' : '1348px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе',
		'CoordX' : '722px',
		'CoordY' : '1469px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, над балконом',
		'CoordX' : '951px',
		'CoordY' : '1510px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Не на самом верху, в углу у колонн',
		'CoordX' : '641px',
		'CoordY' : '1605px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху, над тамплиером',
		'CoordX' : '832px',
		'CoordY' : '1533px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, в углу',
		'CoordX' : '1218px',
		'CoordY' : '1147px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1221px',
		'CoordY' : '1248px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Между домами',
		'CoordX' : '1297px',
		'CoordY' : '1149px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1363px',
		'CoordY' : '1179px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у моря',
		'CoordX' : '1400px',
		'CoordY' : '1188px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На деревянной крыше',
		'CoordX' : '1479px',
		'CoordY' : '971px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На перилах кафедры.',
		'CoordX' : '1549px',
		'CoordY' : '910px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На мосту между стеной и домом.',
		'CoordX' : '1594px',
		'CoordY' : '792px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше часовни',
		'CoordX' : '1730px',
		'CoordY' : '732px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу у башни',
		'CoordX' : '1801px',
		'CoordY' : '750px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, в секторе, 1 уровень.',
		'CoordX' : '1620px',
		'CoordY' : '682px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе дворца, в углу',
		'CoordX' : '1649px',
		'CoordY' : '483px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В фонтане перед храмом',
		'CoordX' : '1277px',
		'CoordY' : '753px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На окне храма',
		'CoordX' : '1347px',
		'CoordY' : '681px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, в дыре',
		'CoordX' : '1333px',
		'CoordY' : '630px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На наземном переходе между зданиями',
		'CoordX' : '1235px',
		'CoordY' : '667px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше дома',
		'CoordX' : '1330px',
		'CoordY' : '437px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, у стены',
		'CoordX' : '1238px',
		'CoordY' : '481px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На помосте, у стены.',
		'CoordX' : '1503px',
		'CoordY' : '393px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, на террасе.',
		'CoordX' : '1512px',
		'CoordY' : '490px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер около лестницы',
		'CoordX' : '1537px',
		'CoordY' : '588px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше, за ширмой.',
		'CoordX' : '1575px',
		'CoordY' : '556px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На колонне, над ступеньками.',
		'CoordX' : '1639px',
		'CoordY' : '541px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у пирса',
		'CoordX' : '1806px',
		'CoordY' : '817px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На земле',
		'CoordX' : '1766px',
		'CoordY' : '588px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше дворца',
		'CoordX' : '1712px',
		'CoordY' : '540px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1515px',
		'CoordY' : '636px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, в дыре',
		'CoordX' : '1509px',
		'CoordY' : '679px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На мосту между зданиями',
		'CoordX' : '1354px',
		'CoordY' : '838px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше ларька',
		'CoordX' : '1449px',
		'CoordY' : '881px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На мосту между домами',
		'CoordX' : '1350px',
		'CoordY' : '975px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, в переулке, в углу',
		'CoordX' : '1308px',
		'CoordY' : '980px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше здания',
		'CoordX' : '1152px',
		'CoordY' : '1016px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балке, между зданиями.',
		'CoordX' : '1159px',
		'CoordY' : '1126px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, угол дома',
		'CoordX' : '1110px',
		'CoordY' : '1266px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1737px',
		'CoordY' : '1322px',
		'Groups' : '[0]',
	},
];
var DamascusPt=[
	{
		'Name' : 'Внизу, в переулке.',
		'CoordX' : '1124px',
		'CoordY' : '566px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На 1 уровне, под навесом.',
		'CoordX' : '1088px',
		'CoordY' : '596px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На 1 уровне',
		'CoordX' : '1131px',
		'CoordY' : '743px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворике',
		'CoordX' : '997px',
		'CoordY' : '761px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворике, под мостом',
		'CoordX' : '1049px',
		'CoordY' : '727px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху, у башни.',
		'CoordX' : '1730px',
		'CoordY' : '623px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На террасе.',
		'CoordX' : '1771px',
		'CoordY' : '716px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, в углу',
		'CoordX' : '1680px',
		'CoordY' : '731px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, 1 уровень.',
		'CoordX' : '1572px',
		'CoordY' : '798px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На террасе',
		'CoordX' : '1594px',
		'CoordY' : '616px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На лестнице',
		'CoordX' : '1488px',
		'CoordY' : '698px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На помосте у стены.',
		'CoordX' : '1385px',
		'CoordY' : '774px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В переулке',
		'CoordX' : '1294px',
		'CoordY' : '669px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1516px',
		'CoordY' : '573px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе',
		'CoordX' : '1385px',
		'CoordY' : '490px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1401px',
		'CoordY' : '428px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внутри базара, на балках',
		'CoordX' : '1419px',
		'CoordY' : '467px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, 1 уровень, на столбе',
		'CoordX' : '1626px',
		'CoordY' : '424px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, 1 уровень',
		'CoordX' : '1531px',
		'CoordY' : '374px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, 1 уровень',
		'CoordX' : '1430px',
		'CoordY' : '339px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху, на шпиле.',
		'CoordX' : '1404px',
		'CoordY' : '303px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1280px',
		'CoordY' : '413px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворике',
		'CoordX' : '1189px',
		'CoordY' : '558px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, во дворе',
		'CoordX' : '996px',
		'CoordY' : '476px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, на дороге, в углу.',
		'CoordX' : '1183px',
		'CoordY' : '622px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе, под навесом',
		'CoordX' : '910px',
		'CoordY' : '635px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '935px',
		'CoordY' : '552px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше мечети',
		'CoordX' : '914px',
		'CoordY' : '467px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балке',
		'CoordX' : '1027px',
		'CoordY' : '275px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху, над деревянным мостом.',
		'CoordX' : '1140px',
		'CoordY' : '345px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В лодке',
		'CoordX' : '1274px',
		'CoordY' : '263px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В лодке, залезать лучше с мостков прыгая по жердям.',
		'CoordX' : '856px',
		'CoordY' : '312px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На веранде.',
		'CoordX' : '1094px',
		'CoordY' : '405px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Между колоннами',
		'CoordX' : '677px',
		'CoordY' : '605px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '713px',
		'CoordY' : '719px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На терасе',
		'CoordX' : '816px',
		'CoordY' : '759px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер посреди дороги',
		'CoordX' : '751px',
		'CoordY' : '799px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На земле, в углу',
		'CoordX' : '778px',
		'CoordY' : '848px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе',
		'CoordX' : '784px',
		'CoordY' : '956px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе',
		'CoordX' : '785px',
		'CoordY' : '1095px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в углу',
		'CoordX' : '704px',
		'CoordY' : '1109px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '584px',
		'CoordY' : '1043px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В пруду',
		'CoordX' : '411px',
		'CoordY' : '1120px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На терасе',
		'CoordX' : '341px',
		'CoordY' : '989px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'У входа в здание, на балках',
		'CoordX' : '240px',
		'CoordY' : '853px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле',
		'CoordX' : '134px',
		'CoordY' : '769px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе, в нише',
		'CoordX' : '181px',
		'CoordY' : '667px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На террасе, над тамплиером.',
		'CoordX' : '91px',
		'CoordY' : '631px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер во дворе',
		'CoordX' : '93px',
		'CoordY' : '670px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На балках, в акре над входом.',
		'CoordX' : '160px',
		'CoordY' : '559px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В углу, на балконе',
		'CoordX' : '84px',
		'CoordY' : '546px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внутри здания, у колонн',
		'CoordX' : '298px',
		'CoordY' : '480px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, в углу',
		'CoordX' : '287px',
		'CoordY' : '578px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, рядом с башней',
		'CoordX' : '376px',
		'CoordY' : '599px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе',
		'CoordX' : '454px',
		'CoordY' : '568px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На кране',
		'CoordX' : '490px',
		'CoordY' : '454px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер',
		'CoordX' : '553px',
		'CoordY' : '300px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '653px',
		'CoordY' : '334px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На веранде',
		'CoordX' : '743px',
		'CoordY' : '301px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе',
		'CoordX' : '806px',
		'CoordY' : '535px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В переулке',
		'CoordX' : '785px',
		'CoordY' : '462px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе',
		'CoordX' : '617px',
		'CoordY' : '504px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На колонне',
		'CoordX' : '678px',
		'CoordY' : '512px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, под аркой',
		'CoordX' : '515px',
		'CoordY' : '695px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На мосту',
		'CoordX' : '361px',
		'CoordY' : '731px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле',
		'CoordX' : '443px',
		'CoordY' : '847px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внутри рынка, в нише',
		'CoordX' : '453px',
		'CoordY' : '910px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внутри рынка, на балках',
		'CoordX' : '372px',
		'CoordY' : '900px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше базара',
		'CoordX' : '651px',
		'CoordY' : '800px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '716px',
		'CoordY' : '946px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе, на земле.',
		'CoordX' : '952px',
		'CoordY' : '1044px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер посреди улицы.',
		'CoordX' : '874px',
		'CoordY' : '1014px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Во дворе, в нише',
		'CoordX' : '865px',
		'CoordY' : '957px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, между домами',
		'CoordX' : '960px',
		'CoordY' : '934px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1032px',
		'CoordY' : '929px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На помосте для крана',
		'CoordX' : '1089px',
		'CoordY' : '870px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, в тупике.',
		'CoordX' : '1149px',
		'CoordY' : '906px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе',
		'CoordX' : '1108px',
		'CoordY' : '978px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1568px',
		'CoordY' : '926px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер во дворе.',
		'CoordX' : '1573px',
		'CoordY' : '900px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Наверху, на палках',
		'CoordX' : '1694px',
		'CoordY' : '850px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, на помосте',
		'CoordX' : '1775px',
		'CoordY' : '879px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1693px',
		'CoordY' : '932px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, во дворе',
		'CoordX' : '1525px',
		'CoordY' : '966px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1464px',
		'CoordY' : '967px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле',
		'CoordX' : '1385px',
		'CoordY' : '888px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше. в нише между домами',
		'CoordX' : '1316px',
		'CoordY' : '877px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер на крыше',
		'CoordX' : '1235px',
		'CoordY' : '861px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше, 1-ый уровень',
		'CoordX' : '1187px',
		'CoordY' : '871px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В проулке, в углу',
		'CoordX' : '1182px',
		'CoordY' : '936px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1247px',
		'CoordY' : '1015px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, внутри здания',
		'CoordX' : '1248px',
		'CoordY' : '959px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе, со стороны улицы.',
		'CoordX' : '1279px',
		'CoordY' : '904px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Над балконом',
		'CoordX' : '1384px',
		'CoordY' : '962px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В пролете, на земле',
		'CoordX' : '1469px',
		'CoordY' : '1030px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1584px',
		'CoordY' : '1078px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1388px',
		'CoordY' : '1072px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе, под крышей',
		'CoordX' : '1343px',
		'CoordY' : '1024px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, на шпиле',
		'CoordX' : '1262px',
		'CoordY' : '1082px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыльце',
		'CoordX' : '1238px',
		'CoordY' : '1156px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, 1 уровень.',
		'CoordX' : '1174px',
		'CoordY' : '1061px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '1122px',
		'CoordY' : '1069px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе, под навесом',
		'CoordX' : '1147px',
		'CoordY' : '1127px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, 1 уровень',
		'CoordX' : '1071px',
		'CoordY' : '1094px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, на крыльце',
		'CoordX' : '1063px',
		'CoordY' : '1165px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, на ступеньке.',
		'CoordX' : '979px',
		'CoordY' : '1094px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Над балконом',
		'CoordX' : '904px',
		'CoordY' : '1095px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер',
		'CoordX' : '1144px',
		'CoordY' : '682px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер',
		'CoordX' : '942px',
		'CoordY' : '396px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер',
		'CoordX' : '1586px',
		'CoordY' : '403px',
		'Groups' : '[1]',
	},
];
var KingdomPt=[
	{
		'Name' : 'Где смотровая башня',
		'CoordX' : '949px',
		'CoordY' : '519px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Где смотровая башня',
		'CoordX' : '155px',
		'CoordY' : '1450px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На телеге слева',
		'CoordX' : '838px',
		'CoordY' : '497px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На телеге справа',
		'CoordX' : '827px',
		'CoordY' : '524px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в углу',
		'CoordX' : '870px',
		'CoordY' : '571px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше здания',
		'CoordX' : '909px',
		'CoordY' : '624px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше на шпиле',
		'CoordX' : '880px',
		'CoordY' : '614px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На смотровой башне',
		'CoordX' : '615px',
		'CoordY' : '498px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в углу',
		'CoordX' : '596px',
		'CoordY' : '481px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше лесов',
		'CoordX' : '679px',
		'CoordY' : '671px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у здания',
		'CoordX' : '986px',
		'CoordY' : '503px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На шесте, посреди деревни на холме',
		'CoordX' : '983px',
		'CoordY' : '559px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше здания, в деревне на холме',
		'CoordX' : '980px',
		'CoordY' : '599px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В деревне на холме, в кустах',
		'CoordX' : '948px',
		'CoordY' : '561px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'У дерева, у воды',
		'CoordX' : '892px',
		'CoordY' : '654px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, между домом и насыпью из глины',
		'CoordX' : '965px',
		'CoordY' : '647px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше глиняного особняка',
		'CoordX' : '936px',
		'CoordY' : '692px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В развалах, на земле',
		'CoordX' : '1009px',
		'CoordY' : '724px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше особняка из глины',
		'CoordX' : '1068px',
		'CoordY' : '724px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер во дворе особняка',
		'CoordX' : '1051px',
		'CoordY' : '707px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Около бочек, во дворе глиняного особняка',
		'CoordX' : '992px',
		'CoordY' : '683px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше сторожевой башни',
		'CoordX' : '1141px',
		'CoordY' : '682px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше сарая',
		'CoordX' : '1208px',
		'CoordY' : '620px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В развалинах около дома',
		'CoordX' : '1167px',
		'CoordY' : '631px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На деревянном кране',
		'CoordX' : '1068px',
		'CoordY' : '604px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у дома',
		'CoordX' : '1055px',
		'CoordY' : '549px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше здания, 1 уровень',
		'CoordX' : '1038px',
		'CoordY' : '566px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе',
		'CoordX' : '1057px',
		'CoordY' : '569px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На балконе дома',
		'CoordX' : '902px',
		'CoordY' : '549px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На отвесном балконе',
		'CoordX' : '903px',
		'CoordY' : '595px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На холме около озера',
		'CoordX' : '1268px',
		'CoordY' : '508px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше сарая',
		'CoordX' : '1207px',
		'CoordY' : '403px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше сарая рядом',
		'CoordX' : '1247px',
		'CoordY' : '412px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На разбитой повозке',
		'CoordX' : '1238px',
		'CoordY' : '422px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у озера',
		'CoordX' : '1286px',
		'CoordY' : '438px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На площадке, где проходят тренинги',
		'CoordX' : '1273px',
		'CoordY' : '365px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На обзорной башне',
		'CoordX' : '1227px',
		'CoordY' : '365px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у обзорной башни',
		'CoordX' : '1402px',
		'CoordY' : '15px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'У сарая, на бочках',
		'CoordX' : '1370px',
		'CoordY' : '90px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В центре лагеря, на бочке',
		'CoordX' : '1415px',
		'CoordY' : '51px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На островке, среди пальм',
		'CoordX' : '1535px',
		'CoordY' : '95px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у палатки',
		'CoordX' : '1482px',
		'CoordY' : '53px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер в углу',
		'CoordX' : '1457px',
		'CoordY' : '559px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше сарая, около обзорной башни',
		'CoordX' : '1425px',
		'CoordY' : '756px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у домушки',
		'CoordX' : '1321px',
		'CoordY' : '766px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше сторожевой вышки, запад',
		'CoordX' : '1261px',
		'CoordY' : '737px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше сторожевой вышки, восток',
		'CoordX' : '1291px',
		'CoordY' : '714px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в горах, рядом конь.',
		'CoordX' : '1366px',
		'CoordY' : '806px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше сторожевой вышки, юг',
		'CoordX' : '1355px',
		'CoordY' : '737px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше сторожевой вышки, север',
		'CoordX' : '1361px',
		'CoordY' : '708px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер за стенкой',
		'CoordX' : '1604px',
		'CoordY' : '1198px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Над акркой особняка',
		'CoordX' : '1599px',
		'CoordY' : '1159px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На южном холме за домом',
		'CoordX' : '1556px',
		'CoordY' : '1215px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер рядом с куличем из глины',
		'CoordX' : '1525px',
		'CoordY' : '1205px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер на западном холме',
		'CoordX' : '1530px',
		'CoordY' : '1102px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Непойми где, под сторожевой вышкой, с краю у скалы, напротив тамплиера.',
		'CoordX' : '1555px',
		'CoordY' : '1140px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Рядом с колодцем, около особняка',
		'CoordX' : '1495px',
		'CoordY' : '1139px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Северный холм, рядом с повозкой',
		'CoordX' : '1620px',
		'CoordY' : '965px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у дома',
		'CoordX' : '1607px',
		'CoordY' : '976px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'У странного дерева, сз холм',
		'CoordX' : '1547px',
		'CoordY' : '1031px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На самом северном холме, рядом с куличами и лавками.',
		'CoordX' : '1526px',
		'CoordY' : '936px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у кулича из глины',
		'CoordX' : '1538px',
		'CoordY' : '994px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер у колодца',
		'CoordX' : '1631px',
		'CoordY' : '1078px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше дома',
		'CoordX' : '1611px',
		'CoordY' : '1074px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На холме, под скалой.',
		'CoordX' : '1646px',
		'CoordY' : '1119px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В канаве у ручья',
		'CoordX' : '1634px',
		'CoordY' : '1018px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, рядом со сторожевой башней',
		'CoordX' : '1322px',
		'CoordY' : '1083px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, рядом с обзорной башней, впритык.',
		'CoordX' : '982px',
		'CoordY' : '1166px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Около домушки',
		'CoordX' : '1048px',
		'CoordY' : '1160px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В центре лагеря',
		'CoordX' : '1048px',
		'CoordY' : '1091px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в горах',
		'CoordX' : '1072px',
		'CoordY' : '914px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер у скалы.',
		'CoordX' : '825px',
		'CoordY' : '1164px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'В крепости, под обзорной башней',
		'CoordX' : '705px',
		'CoordY' : '1359px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, около домика',
		'CoordX' : '693px',
		'CoordY' : '1397px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше двойного дома.',
		'CoordX' : '661px',
		'CoordY' : '1403px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер',
		'CoordX' : '599px',
		'CoordY' : '1388px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На осадной башне',
		'CoordX' : '717px',
		'CoordY' : '1310px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер',
		'CoordX' : '714px',
		'CoordY' : '1278px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На земле, за домом',
		'CoordX' : '732px',
		'CoordY' : '1258px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Под осадной башней',
		'CoordX' : '680px',
		'CoordY' : '1226px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'У скалы',
		'CoordX' : '652px',
		'CoordY' : '1250px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Одинокий домик',
		'CoordX' : '392px',
		'CoordY' : '492px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На перилах, рядом со смотровой башней',
		'CoordX' : '304px',
		'CoordY' : '566px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер на 1 уровне дома.',
		'CoordX' : '311px',
		'CoordY' : '599px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер на скале',
		'CoordX' : '311px',
		'CoordY' : '644px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На пирсе',
		'CoordX' : '167px',
		'CoordY' : '585px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На пирсе, на носу корабля',
		'CoordX' : '223px',
		'CoordY' : '543px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер на пирсе, можно сзади подойти',
		'CoordX' : '210px',
		'CoordY' : '564px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На крыше, на трубе',
		'CoordX' : '250px',
		'CoordY' : '618px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше',
		'CoordX' : '218px',
		'CoordY' : '645px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше сарая',
		'CoordX' : '327px',
		'CoordY' : '710px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше дома-башни',
		'CoordX' : '327px',
		'CoordY' : '740px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На помосте для крана(журавль)',
		'CoordX' : '309px',
		'CoordY' : '698px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше дома, 1 уровень.',
		'CoordX' : '253px',
		'CoordY' : '696px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер на скале',
		'CoordX' : '293px',
		'CoordY' : '758px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Около смотровой вышки за забором',
		'CoordX' : '478px',
		'CoordY' : '1139px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'За забором, за палаткой',
		'CoordX' : '513px',
		'CoordY' : '1128px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На осадной вышке',
		'CoordX' : '550px',
		'CoordY' : '1207px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Около развалин дома, за стенкой',
		'CoordX' : '534px',
		'CoordY' : '1286px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В развалинах дома',
		'CoordX' : '524px',
		'CoordY' : '1181px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В кустах, рядом со смотровой вышкой',
		'CoordX' : '457px',
		'CoordY' : '1335px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер на земле, мимо него бегу.',
		'CoordX' : '438px',
		'CoordY' : '1015px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На высоте острове, между мосиками.',
		'CoordX' : '464px',
		'CoordY' : '948px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Под мостком, с другой стороны острова',
		'CoordX' : '449px',
		'CoordY' : '917px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На земле, слева от скалы.',
		'CoordX' : '435px',
		'CoordY' : '932px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тоже на скале, на возвышении',
		'CoordX' : '417px',
		'CoordY' : '877px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Западная колонна',
		'CoordX' : '959px',
		'CoordY' : '1247px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Восточная колонна',
		'CoordX' : '973px',
		'CoordY' : '1278px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'За стеной на камне',
		'CoordX' : '995px',
		'CoordY' : '1302px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Под лестницей',
		'CoordX' : '936px',
		'CoordY' : '1300px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На низкой колонне',
		'CoordX' : '893px',
		'CoordY' : '1284px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На площадке',
		'CoordX' : '910px',
		'CoordY' : '1317px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху, на самой высокой колонне (с неё прыжок на самую сложную).',
		'CoordX' : '922px',
		'CoordY' : '1341px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На колонне, к северу от самой сложной.',
		'CoordX' : '949px',
		'CoordY' : '1314px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Самая сложная колонна',
		'CoordX' : '943px',
		'CoordY' : '1332px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер в углу',
		'CoordX' : '972px',
		'CoordY' : '1336px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На площадке, незаметный, в кустах',
		'CoordX' : '956px',
		'CoordY' : '1359px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер у озера',
		'CoordX' : '876px',
		'CoordY' : '1472px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'Тамплиер дорожный',
		'CoordX' : '500px',
		'CoordY' : '857px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На деревянном столе,  рядом с другим мини-лагерем, проблемный.',
		'CoordX' : '117px',
		'CoordY' : '1381px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Посреди мини-лагеря',
		'CoordX' : '192px',
		'CoordY' : '1341px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На осадной башне2',
		'CoordX' : '142px',
		'CoordY' : '1320px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На осадной башне',
		'CoordX' : '123px',
		'CoordY' : '1345px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Где мост-кран, на кране.',
		'CoordX' : '94px',
		'CoordY' : '1335px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В яме',
		'CoordX' : '101px',
		'CoordY' : '1310px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В яме2 (в той же яме), иногда их не засчитывают.',
		'CoordX' : '112px',
		'CoordY' : '1292px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Тамплиер, около палатки',
		'CoordX' : '75px',
		'CoordY' : '1280px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'На камне',
		'CoordX' : '1463px',
		'CoordY' : '1273px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На осадной башне',
		'CoordX' : '1583px',
		'CoordY' : '1278px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Рядом с повозкой',
		'CoordX' : '576px',
		'CoordY' : '422px',
		'Groups' : '[0]',
	},
];
var MasyafPt=[
	{
		'Name' : 'Внизу',
		'CoordX' : '593px',
		'CoordY' : '292px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху',
		'CoordX' : '614px',
		'CoordY' : '299px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху',
		'CoordX' : '784px',
		'CoordY' : '660px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На заднем дворе',
		'CoordX' : '649px',
		'CoordY' : '683px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'У обрыва',
		'CoordX' : '563px',
		'CoordY' : '710px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху башни',
		'CoordX' : '497px',
		'CoordY' : '789px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху, 1 уровень',
		'CoordX' : '577px',
		'CoordY' : '803px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, нижний уровень.',
		'CoordX' : '751px',
		'CoordY' : '760px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе, рядом с деревом.',
		'CoordX' : '470px',
		'CoordY' : '868px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Во дворе',
		'CoordX' : '489px',
		'CoordY' : '949px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В углу',
		'CoordX' : '575px',
		'CoordY' : '925px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Наверху башни',
		'CoordX' : '542px',
		'CoordY' : '1000px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу, в углу',
		'CoordX' : '737px',
		'CoordY' : '988px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В углу',
		'CoordX' : '702px',
		'CoordY' : '903px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На крыше, надо было раньше брать',
		'CoordX' : '667px',
		'CoordY' : '845px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'Внизу где библиотека',
		'CoordX' : '326px',
		'CoordY' : '343px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'между 1 и 2, в начальном нападении на масиаф найти невозможно',
		'CoordX' : '832px',
		'CoordY' : '355px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'На холме, рядом с лестницей, за солдатом',
		'CoordX' : '673px',
		'CoordY' : '488px',
		'Groups' : '[0]',
	},
	{
		'Name' : 'В бассейне, на шпиле',
		'CoordX' : '243px',
		'CoordY' : '244px',
		'Groups' : '[1]',
	},
	{
		'Name' : 'В углу',
		'CoordX' : '170px',
		'CoordY' : '179px',
		'Groups' : '[1]',
	},
];
